site_name: "mkdocs-literate-nav"
site_url: "https://oprypin.github.io/mkdocs-literate-nav"
repo_url: "https://github.com/oprypin/mkdocs-literate-nav"
edit_uri: blob/master/docs/
use_directory_urls: false

theme:
  name: material
  features:
    - content.action.edit
    - navigation.tabs
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: teal
    accent: purple

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - !relative $config_dir
  - callouts
  - admonition
  - md_in_html
  - toc:
      permalink: "#"

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  nav:
    absolute_links: ignore

nav:
  - section-index: /mkdocs-section-index/
  - literate-nav:
    - Overview: README.md
    - Reference: reference.md
  - gen-files: /mkdocs-gen-files/
  - same-dir: /mkdocs-same-dir/
  - code-validator: /mkdocs-code-validator/
  - callouts: /markdown-callouts/
